[tool.poetry]
name = "demoproject"
version = "0.1.0"
description = "My demo project"
authors = ["Dejan Đuričić <djuricic1122@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
